spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://swim-cb.cho0w026wkjq.ap-northeast-2.rds.amazonaws.com:5432/swim_cb
    username: swim_cb
    password: Yws6ADPvs2!ibdYs!6jP
