spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  liquibase:
    enabled: false

aws:
  s3:
    host: "https://s3.ap-northeast-2.amazonaws.com"
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

springdoc:
  swagger-ui:
    operations-sorter: alpha

jwt:
  secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: local
    import: classpath:/config/application-oauth2-dev.yaml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000

---

spring:
  config:
    activate:
      on-profile: dev
    import: classpath:/config/application-oauth2-dev.yaml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
