spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  liquibase:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://swim-cb.cho0w026wkjq.ap-northeast-2.rds.amazonaws.com:5432/swim_cb
    username: swim_cb
    password: Yws6ADPvs2!ibdYs!6jP
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  liquibase:
    enabled: false
